[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://attynoda.com/"
  HUGO_CANONIFYURLS = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# カスタムドメインのリダイレクト
[[redirects]]
  from = "https://example.org/*"
  to = "https://attynoda.com/:splat"
  status = 301
  force = true

# 古いドメインからのリダイレクト
[[redirects]]
  from = "https://nodalaw.jp/*"
  to = "https://attynoda.com/:splat"
  status = 301
  force = true

# フィリピン法ノートの記事リダイレクト
[[redirects]]
  from = "/フィリピン法ノート/フィリピン市民権の取得による日本国籍の喪失"
  to = "/posts/フィリピン市民権の取得による日本国籍の喪失"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
