[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://attynoda.com/"
  HUGO_CANONIFYURLS = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# カスタムドメインのリダイレクト
[[redirects]]
  from = "https://example.org/*"
  to = "https://attynoda.com/:splat"
  status = 301
  force = true

# 古いドメインからのリダイレクト
[[redirects]]
  from = "https://nodalaw.jp/*"
  to = "https://attynoda.com/:splat"
  status = 301
  force = true

# フィリピン法ノートの記事リダイレクト（日本語）
[[redirects]]
  from = "/フィリピン法ノート/フィリピン市民権の取得による日本国籍の喪失"
  to = "/posts/フィリピン市民権の取得による日本国籍の喪失"
  status = 301

# フィリピン法ノートの記事リダイレクト（URLエンコーディング）
[[redirects]]
  from = "/%E3%83%95%E3%82%A3%E3%83%AA%E3%83%94%E3%83%B3%E6%B3%95%E3%83%8E%E3%83%BC%E3%83%88/%E3%83%95%E3%82%A3%E3%83%AA%E3%83%94%E3%83%B3%E5%B8%82%E6%B0%91%E6%A8%A9%E3%81%AE%E5%8F%96%E5%BE%97%E3%81%AB%E3%82%88%E3%82%8B%E6%97%A5%E6%9C%AC%E5%9B%BD%E7%B1%8D%E3%81%AE%E5%96%AA%E5%A4%B1"
  to = "/posts/%E3%83%95%E3%82%A3%E3%83%AA%E3%83%94%E3%83%B3%E5%B8%82%E6%B0%91%E6%A8%A9%E3%81%AE%E5%8F%96%E5%BE%97%E3%81%AB%E3%82%88%E3%82%8B%E6%97%A5%E6%9C%AC%E5%9B%BD%E7%B1%8D%E3%81%AE%E5%96%AA%E5%A4%B1"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
